### ISSUE TITLE
Inquiry About Weight File Access Permission and Publication of Downstream Task Code & Parameters

### ISSUE THREAD

**Issue by zoule41** [ToniChopp/ECAMP#2]
Hello,

I am reaching out to inquire about two specific aspects of the ECAMP that are crucial for my research:

Weight File Access Permission:
I have applied for access to the weight files associated with the project but have not yet received approval. Could you please provide an update on the status of my request or guide me on any further steps I need to take to gain access? My application email is "serenazou41@gmail.com".

Publication of Downstream Task Code and Parameter Details:
Additionally, I am keenly interested in the code and detailed parameters for downstream tasks associated with the project. Knowing these details is essential for ensuring the reproducibility of the results and for facilitating further research based on your valuable work. May I kindly know when these details are expected to be made publicly available on the repository?

I understand the challenges and workload that maintaining such a significant project entails. Your assistance and support in providing these resources would immensely benefit the research community, including my ongoing work.

Thank you for your attention to these matters, and I look forward to your prompt response.

Best regards,

Le Zou
National University of Defense Technology

**Comment by ToniChopp** [comment]
Hello,

Thanks for your attention to our work.

I have approved your request for the weight files. Codes for downstream tasks and parameter details are currently in preparation. In the meantime, I recommend temporarily using the fine-tuning code available at [MGCA](https://github.com/HKU-MedAI/MGCA).

**Comment by zoule41** [comment]
> Hello,
> 
> Thanks for your attention to our work.
> 
> I have approved your request for the weight files. Codes for downstream tasks and parameter details are currently in preparation. In the meantime, I recommend temporarily using the fine-tuning code available at [MGCA](https://github.com/HKU-MedAI/MGCA).

Thank you, I have successfully downloaded it. Thank you for sharing!
