### ISSUE TITLE
Hi, 非常感谢您的开源！我们最近在尝试复现这个预训练框架，有些疑问如下

### ISSUE THREAD

**Issue by wangxiao5791509** [ToniChopp/ECAMP#3]
FileNotFoundError: [Errno 2] No such file or directory: **./dataset/minic-cxr-2.0.0-MRMentity-llm.csv**! 

另外，我们最近也在研究 x-ray 的pre-train，想跟您深入沟通下，是否方便加个微信？谢谢！wechat: wangxiao5791509 

![f3e6233cbe3301717042405c873d8db](https://github.com/ToniChopp/ECAMP/assets/12805786/b6e70489-564b-4dc6-ac7c-f32f10597c03)

**Comment by ToniChopp** [comment]
"mimic-cxr-2.0.0-MRM-entity-llm.csv" 这个文件是原始报告和我们蒸馏后的报告的结合版，包含了"img_path", "report", "llm_output" 这三列。 我们蒸馏后的报告可以在[这里](https://drive.google.com/file/d/1I8Q8-sPnLb-kbD93wbCfZ4S_-xdBL3Md/view?usp=drive_link)找到。

The file "mimic-cxr-2.0.0-MRM-entity-llm.csv" is a combined version of the original reports and our distilled reports, containing three columns: "img_path," "report," and "llm_output." You can find our distilled reports [here](https://drive.google.com/file/d/1I8Q8-sPnLb-kbD93wbCfZ4S_-xdBL3Md/view?usp=drive_link).
